### PR TITLE
fix the error for lakehouse monitor

### PR DESCRIPTION
**Pull request by Hehehe421**
The spark.createDataFrame() cannot handle null values in DBR 14.3 LTS, fixed the error in the version

### CODE REVIEW

**Comment by QuentinAmbard** [comment]
Thanks @Hehehe421 . Do you think you could solve the conflict ? You should update your branch

**Comment by Hehehe421** [comment]
Hey @QuentinAmbard , this fix should solve the issue, and I don't have my branch. I used to work on this branch, should I fork my own one and then commit from there? Please advise, thanks a lot!

**Comment by QuentinAmbard** [comment]
can you pull the latest changes and solve the conflict?

**Comment by QuentinAmbard** [comment]
I cherry picked the changes it's in the lastest release, feel free to reopen if something else needs to be changed! Thanks :)

**Pull request closed without merging**
