### PR TITLE
Built the Agent code from playground

### PR DESCRIPTION
**Pull request by sarbaniAi**
**Built the Agent code from playground**

**Below changes are done ->**

- I fixed the agent deployment issue with [Code-based MLflow logging](https://mlflow.org/docs/latest/models.html#models-from-code)-> 

- I created the agent/driver from AI PlayGround and deployed it in the model serving as a review app.
- Evaluation app  is created but the data will be added later in online review app.

**No change :**
External API call to Weather function was commented before my change , Hardcoded parameters are passed to the agent to make the function call successful. it is kept as is as suggested in the feedback document. 

**Changes WIP in the next version **

- Will explore external function and implement the best practices.
- Image Model integration

### CODE REVIEW

**Comment by QuentinAmbard** [comment]
thanks @sarbaniAi ! can you replace the existing files with your improvement instead of creating a new folder? It'll make the review simpler

**Comment by sarbaniAi** [comment]
Hi @QuentinAmbard,  there was only one  file "00-stylist-AI-function-tools-introduction" to replace 

Rest three files are newly created by playground export ->
comfig.yml
agent
driver.

Should I put them all in the same folder "llm-tools-functions"?

I created a folder to separate the agent/driver/config.yml files for Stylist agent.

**Comment by sarbaniAi** [comment]
Hi @QuentinAmbard, 
As I mentioned there are three new files created in this version, Can you please confirm if I should  put all of them in the existing folder "llm-tools-functions"?

**Comment by QuentinAmbard** [comment]
@sarbaniAi let's have a call it'll be easier, I think this is a bit too much for the simple demo, maybe we should keep it for the cookie demo instead, and simplify this one ?

**Comment by sarbaniAi** [comment]
@QuentinAmbard, Ok, tomorrow I am taking off, will connect on Wednesday.

**Comment by sarbaniAi** [comment]
Will create new pull request as per the previous discussion with Quentin - make changes in the main agent code and keep it simple with one  notebook.

**Pull request closed without merging**
