### PR TITLE
add fix for cdf in lakehouse monitoring

### PR DESCRIPTION
**Pull request by renardeinside**

### CODE REVIEW

**Comment by renardeinside** [comment]
The existing code doesn't enable CDF on the table, the fixed version does :)

**Comment by QuentinAmbard** [comment]
@aelhelouDB can you double check this one?

**Review by aelhelouDB — CHANGES_REQUESTED** [review]
The `silver_transaction` table already has CDF enabled when created in the [DataGeneration notebook](./_resources/01-DataGeneration.py). The code to read stream from the CDF is correct, maybe change the comment "Read streams from change data feed" instead

**Comment by renardeinside** [comment]
> The silver_transaction table already has CDF enabled when created in the [DataGeneration notebook](https://github.com/databricks-demos/dbdemos-notebooks/pull/_resources/01-DataGeneration.py).
hey @aelhelouDB , 
last time I was running this demo 2-3 weeks ago and CDF wasn't enabled for `silver_transactions` by default. I guess it might depend on DBR version, therefore doing it explicitly won't hurt.

**Comment by aelhelouDB** [comment]
Not sure why it wasn't enabled if you ran the data generation notebook... (unless when installed via dbdemos it doesn't run the notebook ? @QuentinAmbard ). Let me retry from scratch and see. In any case I agree it wouldn't hurt to add it here since we shouldn't show the data generation notebooks in a demo anyways and should educate customers about the importance of having CDF enabled! but I don't get why you're removing the 
`spark.readstream()` code block...

**Comment by aelhelouDB** [comment]
Hmm looks like you're right @renardeinside , just pulled latest code and for some reason CDF is not enabled by default on the `silver_transactions` table. That being said I think it would be good for demo purposes to emphasize on enabling CDF on monitored tables. @QuentinAmbard you can accept this PR

**Comment by chengyineng38** [comment]
The edit in this PR has been incorporated into the latest [PR](https://github.com/databricks-demos/dbdemos-notebooks/pull/47) instead.

**Pull request closed without merging**
